Add files via upload
vralov/Formula-It-Task pull request #1
Opened 2024-10-18 21:34 UTC by vralov

![image](https://github.com/user-attachments/assets/dbe4a43b-e577-4403-84dd-0a6d61f181fb)

2024-10-19 17:00 UTC, rmushkin requested changes
Пожалуйста, поправьте файлы. Будут вопросы - пишите.

2024-10-19 17:00 UTC, rmushkin commented on Лабораторная работа 1/Фролов, Замена пропущенного элемента средним арифметическим.py
> +for i in range(0, len(numbers)):
Непитонично: в Python цикл `for` умеет перебирать сразу значения итерируемого объекта. Если при этом нужно хранить номер, используйте [enumerate](https://docs.python.org/3/library/functions.html#enumerate).

2024-10-19 17:00 UTC, rmushkin commented on Лабораторная работа 1/Фролов, Замена пропущенного элемента средним арифметическим.py
> +       j = i
А чем вам не нравится просто `i`? :)

2024-10-19 17:00 UTC, rmushkin commented on Лабораторная работа 1/Фролов, Замена пропущенного элемента средним арифметическим.py
> +       sum = 0
`sum` - это встроенная в Python функция. Лучше избегать таких наименований (т. к. после введения этой переменной вы теряете доступ к функции с таким же именем)

2024-10-19 17:00 UTC, rmushkin commented on Лабораторная работа 1/Фролов, Замена пропущенного элемента средним арифметическим.py
> +       j = i
Далее по коду вы никак не меняете `j`, поэтому введение новой переменной избыточно.

2024-10-19 17:00 UTC, rmushkin commented on Лабораторная работа 1/Фролов, Замена пропущенного элемента средним арифметическим.py
> +       for l in range(0, len(numbers)):
История та же, что и в самом первом комменте - непитонично :) Тут как раз лучше использовать ту самую функцию `sum`, которую вы "потеряли" в прошлом комментарии.

2024-10-19 17:00 UTC, rmushkin commented on Лабораторная работа 1/Фролов, Расчет количества книг на дискете.py
Всё нормально, но нарушаете PEP8, записывая математические операторы без пробелов.
Кроме того, выберите ваш стиль и не мешайте в одном файле транслит ("stranic") и английский ("book_volume"). Причём лучше выберите английский.

2024-10-19 20:38 UTC, rmushkin commented
UPD: Осознал, что первая задача решается методами, которые изучаются далее в курсе. Поэтому всё, мною написанное, примите к сведению, но фактически задача засчитывается. 

Исправьте замечания по PEP8 -  и лабораторная будет зачтена 👍

2024-10-22 22:11 UTC, rmushkin commented
Напоминаю, что остался последний шажок :)

2024-10-25 08:36 UTC, rmushkin requested changes
Исправьте, пожалуйста, микрозамечание 🔬 
Кроме того, [добавьте](https://docs.github.com/ru/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository), пожалуйста, меня в список коллабораторов, чтобы я мог закрыть пулл-реквест.

2024-10-25 08:36 UTC, rmushkin commented on Лабораторная работа 1/Фролов, Расчет количества книг на дискете.py
> +import math
[PEP8](https://peps.python.org/pep-0008/): импорт нужно отбить двумя пустыми строками

2024-10-25 08:36 UTC, rmushkin commented on Лабораторная работа 1/Фролов, Замена пропущенного элемента средним арифметическим.py
> +        numbers[i] = 0
Ох, `S` - крайне плохое имя для переменной. В Python с большой буквы называют классы.
[PEP8](https://peps.python.org/pep-0008/) (указания по стилю написания кода): имена переменных должны быть целыми (сокращайте, только если это обзепринятое обозначение, или если без сокращения будет очень плохо), понятными английскими словами (если несколько, то разделёнными подчёркиваниями и всеми с маленькой буквы).

2024-10-25 18:47 UTC, rmushkin commented
Принято ✅ 
Теперь [добавьте](https://docs.github.com/ru/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository), пожалуйста, меня в список коллабораторов, чтобы я мог закрыть пулл-реквест.

2024-10-25 18:56 UTC, vralov commented
Приглашение в список коллабораторов отправил

2024-10-25 18:58 UTC, merged