Add files via upload
vralov/Formula-It-Task pull request #2
Opened 2024-10-24 16:43 UTC by vralov

Внес правки в первую лабораторную, загрузил вторую.

![image](https://github.com/user-attachments/assets/225db63a-555d-4e93-9c0a-ca85c9f7fc53)

2024-10-29 18:41 UTC, rmushkin requested changes
Поправьте, пожалуйста, одну задачу.

2024-10-29 18:41 UTC, rmushkin commented on Лабораторная работа 2/Фролов, Продолжение финансового планирования.py
> +for i in range(1, months + 1):
1. (не ошибка) питоничнее использовать _ вместо имени переменной. Это полностью валидное имя, т. к. нижнее подчёркивание считается обычной буквой; однако выглядит как "пустое место" и дополнительно самодокументирует код, указывая на неиспользуемость значения.
2. Тоже не ошибка, но зачем?! Зачем прибавлять по 1 и к началу, и к концу отрезка, если всё, что нам нужно - это лишь его длина?

2024-10-29 18:41 UTC, rmushkin commented on Лабораторная работа 2/Фролов, Продолжение финансового планирования.py
> +print(f"Подушка безопасности, чтобы протянуть {months} месяцев без долгов:", round(money_capital))
Ловушка с `round`: 3 рублей не хватит, чтобы купить гвоздь за 3 рубля 25 копеек. Надо округлять в большую сторону.

2024-10-31 16:15 UTC, vralov commented
![image](https://github.com/user-attachments/assets/963b2cdc-06d8-4eb0-ba81-5b9eea194c2d)
Не отправленные комментарии

2024-11-01 19:06 UTC, rmushkin commented
К сожалению, в задании ошибка. Мы уже связались с авторами курса и ожидаем исправления в ближайшее время. Но факт остаётся фактом - нужно округлять вверх. Вы можете сами убедиться в этом, если введёте число-ответ из второй задачи в первую и посчитаете месяцы (поправив, конечно, инфлацию, чтобы она была одинаковой).

2024-11-01 20:15 UTC, merged